# nixpacks.toml

[phases.setup]
# Mantemos as bibliotecas essenciais para o Chrome rodar "saudável" e com fontes
nixPkgs = [
    "nss",
    "freetype",
    "harfbuzz",
    "ca-certificates",
    "ttf-freefont"
]

[variables]
# REMOVIDO: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
# REMOVIDO: PUPPETEER_EXECUTABLE_PATH
# Deixamos o Puppeteer gerenciar o binário, mas usando as libs acima.