# nixpacks.toml

[phases.setup]
# Mantemos as bibliotecas essenciais para o Chrome rodar
nixPkgs = [
    "nss",
    "freetype",
    "harfbuzz",
    "ca-certificates",
    "ttf-freefont"
]

[phases.install]
# ALTERAÇÃO CRÍTICA:
# Substituímos o padrão "npm ci" por "npm install".
# Isso força a atualização das dependências (Puppeteer e wwebjs)
# ignorando o conflito com o arquivo de bloqueio antigo.
cmds = ["npm install"]