# nixpacks.toml

[phases.setup]
# Mantemos a instalação dos pacotes necessários
nixPkgs = [
    "chromium",
    "nss",
    "freetype",
    "harfbuzz",
    "ca-certificates",
    "ttf-freefont"
]

[variables]
# Dizemos ao Puppeteer para NÃO baixar o navegador dele (pois vamos usar o do sistema)
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

